name: WFCCI

on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Transfer issue
        uses: dpanayotov/issue-cloner@v0.2
        with:
            label: "clone"
            targetRepo: mentorchita/newgen
            token: ${{ secrets.SECTRET_TOCKEN }}  
