name: WFCCI

on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: iaia/issue-copier@v1.2
        with:
          GITHUB_OWNER: 'mentorchita'
          GITHUB_REPOSITORY: 'GenerationTech'
          GITHUB_DEST_REPOSITORY: 'newgen'
          GITHUB_ACCESS_TOKEN:  ${{secrets.SECTRET_TOCKEN}}
